# Generated by Django 5.1.4 on 2024-12-29 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_remove_post_data_post_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
