# Generated by Django 5.1.4 on 2025-01-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(choices=[('SAL', 'Salvador - R$400,00'), ('VIC', 'Vitória da Conquista - R$150,00')], max_length=3)),
                ('horario', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagens.viagem')),
            ],
        ),
        migrations.CreateModel(
            name='GastoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagens.viagem')),
            ],
        ),
    ]
