# Generated by Django 5.1.4 on 2025-01-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='total_passageiros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
