# Generated by Django 5.1.4 on 2025-01-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_viagem_total_passageiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
