# Generated by Django 5.1.4 on 2025-01-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_viagem_total_gastos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoextra',
            name='motivo',
        ),
        migrations.AddField(
            model_name='gastoextra',
            name='descricao',
            field=models.TextField(default='Gastos'),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_extras', to='viagens.viagem'),
        ),
    ]
