# Generated by Django 5.1.4 on 2025-01-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_remove_gastoextra_motivo_gastoextra_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='nome_motorista',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.CharField(choices=[('SSA', 'Salvador - R$200,00'), ('VCA', 'Vitória da Conquista - R$75,00')], max_length=3),
        ),
    ]
