# Generated by Django 5.1.4 on 2025-01-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0006_viagem_excluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='motorista_whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
